const questions = [
    {
        id: 1,
        question: 'In which continent is Suriname?',
        option1: 'Asia',
        option2: 'South America',
        option3: 'Europe',
        option4: 'Africa',
        answer: 'South America',
        explanation: 'It borders Brazil, Guayana and French Guyana, and has Atlantic coastline.',
        points: 1,
    },
    {
        id: 2,
        question: 'In which US state is Memphis?',
        option1: 'Tennessee',
        option2: 'Alabama',
        option3: 'Maine',
        option4: 'Florida',
        answer: 'Tennessee',
        explanation: 'The home of Elvis! What else needs to be said?',
        points: 1,
    },
    {
        id: 3,
        question: 'Which city boasts the world\'s highest international airport?',
        option1: 'Geneva',
        option2: 'kathmandu',
        option3: 'La Paz',
        option4: 'Lhasa',
        answer: 'La Paz',
        explanation: 'Bolivia\'s capital is the highest in the world. It\s airport sits at  4,061.5m (13,325 ft).',
        points: 1,
    },
    {
        id: 4,
        question: 'Which of these cities has an extinct volcano?',
        option1: 'New York',
        option2: 'Edinburgh',
        option3: 'Paris',
        option4: 'Stockholm',
        answer: 'Edinburgh',
        explanation: 'Arthur\'s seat is an extinct volcano. Millions of tourists climb it each year.',
        points: 1,
    },
    {
        id: 5,
        question: 'How many African countries does the equator pass through',
        option1: 'four',
        option2: 'six',
        option3: 'seven',
        option4: 'ten',
        answer: 'seven',
        explanation: 'From east to west: Sao Tome and Principe, Gabon, Congo, DR Congo, Uganda, Kenya, and Somalia.',
        points: 1,
    },


]

export default questions